import type { Metadata } from "next";
import { LingoProvider, loadDictionary } from "lingo.dev/react/rsc";
import { Geist, Geist_Mono } from "next/font/google";
import CustomTamboProvider from "@/components/CustomTamboProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <LingoProvider loadDictionary={(locale) => loadDictionary(locale)}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CustomTamboProvider>{children}</CustomTamboProvider>
        </body>
      </html>
    </LingoProvider>
  );
}
